### ISSUE TITLE
building uboot for MR33

### ISSUE THREAD

**Issue by greghutchins** [riptidewave93/LEDE-MR33#11]
Do you have a source tree and build instructions for u-boot specifically for the MR33?
I can see there is a u-boot-2015.10 directory created in the build_dir/target-arm-cortex* 
directory but there is no specific config file in the "configs" or "board" directory.
Thanks

**Comment by riptidewave93** [comment]
U-Boot is not packaged for the MR33 within LEDE. If you want to play with the Meraki U-Boot source, I have a copy uploaded at https://github.com/riptidewave93/meraki-uboot/tree/mr33-20170427. This is what was used to build the custom U-Boot used for flashing.

**Comment by greghutchins** [comment]
Thanks for your reply -- I added another issue to your meraki-uboot repository Issues tab.
