### ISSUE TITLE
No TFTP connection

### ISSUE THREAD

**Issue by slizzered** [riptidewave93/LEDE-MR33#14]
Hey there!
First of all, thank you very much for your effort with this project.
I tried following the instructions on GoogleDrive, but I ran into a problem:
Transferting the uboot-image works without a problem, but afterwards the script exits and I don't see a TFTP server starting up. Transferring files to the DUT only results in a timeout error.

It is possible to ping 192.168.1.1, but otherwise no connection can be established via Ethernet.
The colored LED stays constantly in a reddish-orange color, just as it did while transferring the uboot-image.  

This might be similar to this comment, where no message about TFTP is displayed:
https://github.com/riptidewave93/LEDE-MR33/issues/1#issuecomment-420016794

I realize that I should initialize a connection, but don't manage to do so (using a fairly recent Linux Distro and `tftp`).
Any Ideas?

Cheers!

```
Progress 99.9%,  0.2kb/s, ETA 1.0s
Progress 100%                            
COM: kernel from Legacy Image at 82000000 ...
   Image Name:   MR33-UBOOT-1
   Image Type:   ARM Linux Kernel Image (gzip compressed)
   Data Size:    171744 Bytes = 167.7 KiB
   Load Address: 86000000
   Entry Point:  86000000
   Verifying Checksum ... O
COM: K
   Uncompressing Kernel Image ... 
COM: OK
Using machid 0x8010001 from environment

Starting kernel ...



U-Boot 2012.07-ga8496ca-dirty [local,local] (Mar 10 2018 - 09:10:50)

DRAM:  242 MiB
machid : 0x8010001

COM: Product: meraki_Stinkbug
NAND:  ONFI device found
ID = 1d80f101
Vendor = 1
Device = f1
128 MiB
Using default environment

In:    serial
Out:   serial
Err:   serial
machid: 8010001

COM: Net:   
COM: MAC0 addr:0:3:7f:ba:db:ad
PHY ID1: 0x4d
PHY ID2: 0xd072
ipq40xx_ess_sw_init done
eth0
Hit any key to stop autoboot: 11 
CO10 
CO 9 
CO 8 
CO 7 
CO 6 
CO 5 
CO 4 

CO 3 
CO 2 
CO 1 
CO 0 
Hello from MR33 U-BOOT
Creating 1 MTD partitions on "nand0":
0x000000c00000-0x000007c00000 : "mtd=0"
```

```
# echo -e "binary\nput openwrt-18.06.1-ipq40xx-meraki_mr33-initramfs-fit-uImage.itb" | tftp 192.168.1.1  
tftp> binary
tftp> put openwrt-18.06.1-ipq40xx-meraki_mr33-initramfs-fit-uImage.itb
Transfer timed out.
```

**Comment by DrKinGpinG** [comment]
I have the exact same U-Boot and just flashed mine yesterday. At the beginning I had the same problem as you with the tftp client from linux so I have changed to PumpKIN TFTP on Windows 10 and was able to successfully upload the image. Maybe worth a try.

**Comment by danielbald** [comment]
@DrKinGpinG thank you very much, that worked for me 😄

**Comment by slizzered** [comment]
This worked for me as well, apparently the problem is with my TFTP client. Thank you very much, @DrKinGpinG
