### ISSUE TITLE
MR33 flashed wrong firmware

### ISSUE THREAD

**Issue by freedomnotfree852** [riptidewave93/LEDE-MR33#17]
Hello,

I have two routers are flashed Openwrt on my network, I want to upgrade the .bin firmware to another one but flashed to the MR33 by mistake. Unfortunately, MR33 LED keep solid orange, also I tried connect to TTL serial to get more info, it showing the u-boot booting until to the "Loading Kernel Image" and then keep looping.

Anybody have any idea help me to fix it
Many thanks! Merry Christmas!

**Comment by riptidewave93** [comment]
@freedomnotfree852 Since u-boot isn't affected by flashing OpenWRT, just go through the flashing document again and this should allow you to re-flash OpenWRT on the device.
