### ISSUE TITLE
Not really an issue more of a question

### ISSUE THREAD

**Issue by Smurfy37** [riptidewave93/LEDE-MR33#19]
Hi I do a lot of pulling chips off boards and looking at what makes them tick I'm curious if I could just remove the NAND and flash the sysupgrade as I'm not sure what uboot bin and the upgrade bin do I'm wondering if its literally a case where I can reflash the NAND and not worry about blowing efuses on my 2017 firmware? im presuming the uboot is a partition on the NAND chip and reflashing with the sysupgrade wont allow it to boot properly and then if i put the uboot on i wont be able to boot because ive got nothing to uboot into?

**Comment by riptidewave93** [comment]
@Smurfy37 please see https://github.com/riptidewave93/LEDE-MR33/issues/13 as people have previously successfully reprogrammed the NAND manually to downgrade the bootloader.
