### ISSUE TITLE
ATH10K firmware blobs

### ISSUE THREAD

**Issue by jebuskrust** [riptidewave93/LEDE-MR33#3]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=7344ec9e1df9e27d105ed48d2db99e22370236de

Are you're needing these?

**Comment by riptidewave93** [comment]
We already have the blobs we need as they are in OpenWRT. Defined at https://github.com/riptidewave93/LEDE-MR33/blob/master/overlay/target/linux/ipq806x/image/Makefile#L116 and package is at https://github.com/openwrt/openwrt/blob/master/package/firmware/ath10k-firmware/Makefile#L230
