### ISSUE TITLE
5ghz and higher channels

### ISSUE THREAD

**Issue by Ezoxu** [riptidewave93/LEDE-MR33#4]
Hello, Chris.
Awesome work, flash was successful, even with chinese cable :) 
I have a question though - did you have any problems with setting higher channels? I'm trying to run my network on VHT80, Channel 132, region is set to US. And the wireless interface just doesn't start. Lower channels - 36, 40 and higher - work fine. 

I'm using wrt3200acm currently, on dd-wrt though, and it works fine with this config.

Thank you in advance.

**Comment by Ezoxu** [comment]
Right, it seems it is the DFS problem.
Cannot find the line in config file. Is it built with DFS support?

**Comment by chunkeey** [comment]
You could check 
           `# iw reg get`

This will dump your current regulatory.db in a readable format:

    country US: DFS-FCC
        (2402 - 2472 @ 40), (N/A, 30), (N/A)
        (5170 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
        (5250 - 5330 @ 80), (N/A, 23), (0 ms), DFS, AUTO-BW
        (5490 - 5730 @ 160), (N/A, 23), (0 ms), DFS
        (5735 - 5835 @ 80), (N/A, 30), (N/A)
        (57240 - 63720 @ 2160), (N/A, 40), (N/A)

Note: 
The tricky part about DFS-Channels is that the hardware will have to listen to the channel for a while, before it can start operating. This is part of the 802.11 spec. That said, I found these "Best Practice"
guides over at ieee802 http://www.ieee802.org/18/Meeting_documents/2007_Nov/WFA-DFS-Best%20Practices.pdf much easier to understand (look at page 14-15).
