### ISSUE TITLE
TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by Turb0Yoda** [riptidewave93/LEDE-MR33#6]
After having issues with python serial and serial dependencies, I finally got to this error:

Tried both Windows 10 and Arch.

```python .\ubootwrite.py --write=mr33-uboot.bin
Uploading image
Traceback (most recent call last):
  File ".\ubootwrite.py", line 221, in <module>
    main()
  File ".\ubootwrite.py", line 216, in main
    upload(ser, options.write, int(options.size, 0), int(options.addr, 0), options.verbose, debug, options.shell)
  File ".\ubootwrite.py", line 170, in upload
    ret = memwrite(ser, path, size, start_addr, verbose, debug, shell)
  File ".\ubootwrite.py", line 93, in memwrite
    prompt = getprompt(ser, start_addr, verbose, shell)
  File ".\ubootwrite.py", line 37, in getprompt
    combined = oldbuf+buf
TypeError: must be str, not bytes```

**Comment by jebuskrust** [comment]
What version of python are you running by chance?

I'm running 2.7.13 on my Pi here, and had no issues running this script.
You can run the following and it will tell you
python -V

**Comment by riptidewave93** [comment]
@chunkeey may have some feedback on this issue.

**Comment by chunkeey** [comment]
I would need to know the python version.
The (MR33 specific) ubootwrite.py script calls for python2.7 

      #!/usr/bin/env python2.7

The "TypeError: must be str, not bytes```" error however are likely a result of a python 3.5 or 3.6?.

**Comment by Turb0Yoda** [comment]
I had a different error with 2.7
Unfortunately, my MR33 decided to not power on one day when I came back, shortly after I posted the question.

RIP unused MR33.

**Comment by chunkeey** [comment]
:disappointed:  Any idea what killed it? ESD Damage :zap: ? Wrong polarity on the serial ports (yeah, this is really deadly too, even with relatively low voltages and amps)?

**Comment by Turb0Yoda** [comment]
Unfortunately I have no idea. It was working when I left for class. I turned it off, hadn't plugged in any serial cable for a week. Came back and it hasn't turned on since.

**Comment by riptidewave93** [comment]
@TurboYoda going to close this issue out, feel free to re-open as needed.
